### ISSUE TITLE
Adecuación campos linaje

### ISSUE THREAD

**Issue by ronmoy007** [Millan13/dpa_equipo2#21]
Puesto que la lista de campos para seleccionar y deseleccionar quedaron juntos, agregar una manera de distinguirlos para sólo tomar en cuenta los campos correctos al momento de crear el csv que se inserta a linaje

**Comment by lauragmz** [comment]
Se modificaron los archivos Rita.py y Luigi_Tasks.py
En Rita.py se modificó el diccionario de campos a activar, incluyendo una bandera que permitiera disintiguir los campos a activar de los campos a desactivar.
En Luigi_Tasks.py se adecuó el llenado de la tabla de linaje Archivos_Det (incluida en el método WebScrapping_Inicial) para que considerara únicamente los campos marcados con bandera de activar en Rita.py
